### ISSUE TITLE
# keyword not highlighted

### ISSUE THREAD

**Issue by zbyti** [michalkolodziejski/ST3-action-syntax-highlighting#3]
```
PROC SEARCH()
 FOR X=0 TO D
  DO
   Y=X*8 B=1
   FOR A=0 TO 7
    DO
     IF T(Y+A)#O(A) THEN B=0 FI
    OD
   IF B=1 THEN RETURN FI
  OD
RETURN
```

![Screenshot_2020-04-24_16-24-35](https://user-images.githubusercontent.com/14273557/80223980-59781d00-8649-11ea-8efe-824ccf3c61ca.png)

**Comment by michalkolodziejski** [comment]
@zbyti - **#** is an operator - I have missed it in list

**Comment by zbyti** [comment]
Yes, it's operand. Thanks for fixing it! :+1:
