### ISSUE TITLE
variables should get highlighted with other color than white

### ISSUE THREAD

**Issue by michalkolodziejski** [michalkolodziejski/ST3-action-syntax-highlighting#4]

**Comment by zbyti** [comment]
I suggest changing the color of constants (values) with variables.

**Comment by michalkolodziejski** [comment]
@zbyti how about this one?

1) ![Zrzut ekranu 2020-04-27 18 44 03](https://user-images.githubusercontent.com/1325665/80397912-2cc93d00-88b7-11ea-9c40-8dd5d99b2cb8.png)

vs

2) ![Zrzut ekranu 2020-04-27 20 34 17](https://user-images.githubusercontent.com/1325665/80408116-f5fb2300-88c6-11ea-8a61-cb7a4f947a0d.png)

which way do You prefer?

**Comment by zbyti** [comment]
First one :]
